apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ibm-golang-test
  annotations:
    description: Executes build, test, and sonarscan logic for a Golang application
    app.openshift.io/description: Executes build, test, and sonarscan logic for a Golang application
    app.openshift.io/vcs-uri: https://github.com/IBM/ibm-garage-tekton-tasks
    app.openshift.io/vcs-ref: master
  labels:
    version: 0.0.0
spec:
  params:
    - name: git-url
      type: string
      description: The git repository url
    - name: revision
      type: string
      description: The branch, tag, or git reference from the git git-url location
    - name: image-url
      type: string
      description: "The location where to push the image in the form of <server>/<namespace>/<repository>:<tag>"
    - name: app-name
      type: string
      description: The name of the image that will be built for the application
    - name: source-dir
      type: string
      default: /source
    - name: golang-image
      type: string
      default: golang:stretch
    - name: sonarqube-cli
      type: string
      default: sonarsource/sonar-scanner-cli
  volumes:
    - name: source
      emptyDir: {}
  stepTemplate:
    envFrom:
      - configMapRef:
          name: pactbroker-config
          optional: true
  steps:
    - name: git-clone
      image: alpine/git
      command: ["/bin/sh"]
      args:
        - -c
        - |
          git clone $(params.git-url) $(params.source-dir)
          cd $(params.source-dir)
          git checkout $(params.revision)
          echo "IMAGE_NAME=$(basename $(git rev-parse --show-toplevel))" >> ./.env-config
      volumeMounts:
        - name: source
          mountPath: $(params.source-dir)
    - name: build
      image: $(params.golang-image)
      workingdir: $(params.revision)
      command: ["/bin/bash"]
      args:
        - -c
        - |
          set -e
          go build ./...
      volumeMounts:
        - name: source
          mountPath: $(params.source-dir)
    - name: test
      image: $(params.golang-image)
      workingdir: $(params.revision)
      command: ["/bin/bash"]
      args:
        - -c
        - |
          set -e
          go test ./...
      volumeMounts:
        - name: source
          mountPath: $(params.source-dir)
    - name: sonar-scan
      image: $(params.sonarqube-cli)
      workingdir: $(params.source-dir)
      envFrom:
        - configMapRef:
            name: sonarqube-config
            optional: true
        - secretRef:
            name: sonarqube-access
            optional: true
      env:
        - name: SONAR_USER_HOME
          value: $(params.revision)
      command: ["/bin/bash"]
      args:
        - -c
        - |
          set -e

          if ! command -v sonar-scanner &> /dev/null
          then
              echo "Skipping SonarQube step, no task defined"
              exit 0
          fi

          if [ -n "${SONARQUBE_URL}" ]; then

            sonar-scanner -X \
            -Dsonar.login=${SONARQUBE_USER} \
            -Dsonar.password=${SONARQUBE_PASSWORD} \
            -Dsonar.host.url=${SONARQUBE_URL} \
            -Dsonar.projectKey=${IMAGE_NAME}

          else
              echo "Skipping Sonar Qube step for now but include"
          fi
      volumeMounts:
        - name: source
          mountPath: $(params.source-dir)
