apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: igc-java-maven-test
spec:
  params:
    - name: git-url
      type: string
      description: The git repository url
    - name: revision
      type: string
      description: The branch, tag, or git reference from the git git-url location
    - name: image-url
      type: string
      description: "The location where to push the image in the form of <server>/<namespace>/<repository>:<tag>"
    - name: image-name
      type: string
      description: The name of the image that will be built for the application
    - name: source-dir
      type: string
      default: /source
    - name: maven-image
      type: string
      default: maven:3.6.3-jdk-11-slim
    - name: sonarqube-cli
      type: string
      default: sonarsource/sonar-scanner-cli
  volumes:
    - name: source
      emptyDir: {}
  steps:
    - name: git-clone
      image: alpine/git
      command: ["/bin/sh"]
      args:
        - -c
        - |
          git clone $(params.git-url) $(params.source-dir)
          cd $(params.source-dir)

          git reset --hard $(params.revision)

          echo ""
          echo "REVISION: $(params.revision)"
          echo "SOURCE_DIR: $(params.source-dir)"
          echo "IMAGE_URL: $(params.image-url)"
          echo "IMAGE_NAME: $(params.image-name)"
      volumeMounts:
        - name: source
          mountPath: $(params.source-dir)
    - name: build
      image: $(params.maven-image)
      workingdir: $(params.source-dir)
      command: ["/bin/bash"]
      args:
        - -c
        - |
          set -e
          mvn package
      volumeMounts:
        - name: source
          mountPath: $(params.source-dir)
    - name: test
      image: $(params.maven-image)
      workingdir: $(params.source-dir)
      command: ["/bin/bash"]
      args:
        - -c
        - |
          set -e
          mvn test
      volumeMounts:
        - name: source
          mountPath: $(params.source-dir)
    - name: sonar-scan
      image: $(params.sonarqube-cli)
      workingdir: $(params.source-dir)
      envFrom:
        - configMapRef:
            name: sonarqube-config
            optional: true
        - secretRef:
            name: sonarqube-access
            optional: true
      env:
        - name: SONAR_USER_HOME
          value: $(params.revision)
      command: ["/bin/bash"]
      args:
        - -c
        - |
          set -e

          IMAGE_NAME=$(params.image-name)

          if ! command -v sonar-scanner &> /dev/null
          then
              echo "Skipping SonarQube step, no task defined"
              exit 0
          fi

          if [ -n "${SONARQUBE_URL}" ]; then

            sonar-scanner -X \
            -Dsonar.login=${SONARQUBE_USER} \
            -Dsonar.password=${SONARQUBE_PASSWORD} \
            -Dsonar.host.url=${SONARQUBE_URL} \
            -Dsonar.projectKey=${IMAGE_NAME}

          else
              echo "Skipping Sonar Qube step for now but include"
          fi
      volumeMounts:
        - name: source
          mountPath: $(params.source-dir)
