apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: igc-deploy
  labels:
    version: 0.0.0
spec:
  params:
    - name: git-url
      type: string
      description: The git repository url
    - name: revision
      description: The git reference that was checked out
    - name: image-url
      type: string
      description: "The location where to push the image in the form of <server>/<namespace>/<repository>:<tag>"
      default: ""
    - name: image-name
      type: string
      description: The name of the application image
      default: ""
    - name: source-dir
      type: string
      default: /source
    - name: js-image
      type: string
      default: docker.io/node:12-stretch
    - name: tools-image
      type: string
      default: garagecatalyst/ibmcloud-dev:1.0.10
  volumes:
    - name: source
      emptyDir: {}
  steps:
    - name: git-clone
      image: alpine/git
      command: ["/bin/sh"]
      args:
        - -c
        - |
          git clone $(params.git-url) $(params.source-dir)
          cd $(params.source-dir)

          git reset --hard $(params.revision)

          echo ""
          echo "REVISION: $(params.revision)"
          echo "SOURCE_DIR: $(params.source-dir)"
          echo "IMAGE_URL: $(params.image-url)"
          echo "IMAGE_NAME: $(params.image-name)"
      volumeMounts:
        - name: source
          mountPath: $(params.source-dir)
    - name: helm-deploy
      image: $(params.tools-image)
      workingdir: $(params.source-dir)
      env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: BRANCH
          value: $(params.revision)
      envFrom:
        - configMapRef:
            name: ibmcloud-config
      command: ["/bin/bash"]
      args:
        - -c
        - |
          set -e

          ENVIRONMENT_NAME="${NAMESPACE}"

          REPO_URL=$(params.git-url)
          IMAGE_URL=$(params.image-url)
          IMAGE_NAME=$(params.image-name)
          IMAGE_VERSION=$(params.revision)

          REGISTRY_URL=$(echo $IMAGE_URL | awk -F / '{print $1}')
          REGISTRY_NAMESPACE=$(echo $IMAGE_URL | awk -F / '{print $2}')

          echo "REGISTRY_URL: $REGISTRY_URL"
          echo "REGISTRY_NAMESPACE: $REGISTRY_NAMESPACE"
          echo "IMAGE_NAME: $IMAGE_NAME"
          echo "IMAGE_VERSION: $IMAGE_VERSION"

          export CHART_ROOT=$(find . -name chart)
          echo "CHART_ROOT: $CHART_ROOT"

          export CHART=$(find . -name Chart*.yaml)
          echo "CHART: $CHART"

          export CHART_NAME=$(cat $CHART | awk '/name:/ {print $2}')
          echo "CHART_NAME: $CHART_NAME"

          # Update Chart name and version
          if [[ "${CHART_NAME}" != "${IMAGE_NAME}" ]]; then
            echo "Renaming chart from ${CHART_NAME} to ${IMAGE_NAME}"
            cp -R "${CHART_ROOT}/${CHART_NAME}" "${CHART_ROOT}/${IMAGE_NAME}"
            cat "${CHART_ROOT}/${CHART_NAME}/Chart.yaml" | \
                yq w - apiVersion "v1" | \
                yq w - name "${IMAGE_NAME}" > "${CHART_ROOT}/${IMAGE_NAME}/Chart.yaml"
          else
            echo "Chart name and image name match: ${IMAGE_NAME}"
          fi

          CHART_PATH="${CHART_ROOT}/${IMAGE_NAME}"

          RELEASE_NAME="${IMAGE_NAME}"
          echo "RELEASE_NAME: $RELEASE_NAME"

          echo "INITIALIZING helm with client-only (no Tiller)"
          helm init --client-only 1> /dev/null 2> /dev/null
          echo $(helm version --client)

          echo "CHECKING CHART (lint)"
          helm lint ${CHART_PATH}

          IMAGE_REPOSITORY="${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}"

          INGRESS_ENABLED=true
          ROUTE_ENABLED=false
          if [[ "${CLUSTER_TYPE}" == "openshift" ]]; then
            INGRESS_ENABLED=false
            ROUTE_ENABLED=true
          fi

          # Update helm chart with repository and tag values
          cat ${CHART_PATH}/values.yaml | \
              yq w - nameOverride "${IMAGE_NAME}" | \
              yq w - fullnameOverride "${IMAGE_NAME}" | \
              yq w - vcsInfo.repoUrl "${REPO_URL}" | \
              yq w - vcsInfo.branch "${BRANCH}" | \
              yq w - image.repository "${IMAGE_REPOSITORY}" | \
              yq w - image.tag "${IMAGE_VERSION}" | \
              yq w - ingress.enabled "${INGRESS_ENABLED}" | \
              yq w - route.enabled "${ROUTE_ENABLED}" > ./values.yaml.tmp
          cp ./values.yaml.tmp ${CHART_PATH}/values.yaml
          cat ${CHART_PATH}/values.yaml

          # Using 'upgrade --install" for rolling updates. Note that subsequent updates will occur in the same namespace the release is currently deployed in, ignoring the explicit--namespace argument".
          helm template ${CHART_PATH} \
              --name ${RELEASE_NAME} \
              --namespace ${ENVIRONMENT_NAME} \
              --set ingress.tlsSecretName="${TLS_SECRET_NAME}" \
              --set ingress.subdomain="${INGRESS_SUBDOMAIN}" > ./release.yaml

          echo -e "Generated release yaml for: ${ENVIRONMENT_NAME}/${IMAGE_NAME}"
          cat ./release.yaml

          echo -e "Deploying into: ${ENVIRONMENT_NAME}/${IMAGE_NAME}"
          kubectl apply -n ${ENVIRONMENT_NAME} -f ./release.yaml --validate=false > results.out
          cat results.out

          echo "Waiting for rollout of ${ENVIRONMENT_NAME}/${IMAGE_NAME}"
          cat results.out | \
            grep -E "deployment|statefulset" | \
            sed "s/deployment.apps/deployment/g" | \
            sed "s/statefulset.apps/statefulset/g" | \
            sed "s/configured//g" | \
            sed "s/unchanged//g" | while read target; do

            echo "Waiting for rollout of ${target} in ${ENVIRONMENT_NAME}"
            kubectl rollout status -n ${ENVIRONMENT_NAME} ${target}
          done
      volumeMounts:
        - name: source
          mountPath: $(params.source-dir)
