apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: igc-liberty-server-check
spec:
  params:
    - name: git-url
      type: string
      description: The git repository url
    - name: revision
      description: The git reference that was checked out
    - name: image-url
      type: string
      description: "The location where to push the image in the form of <server>/<namespace>/<repository>:<tag>"
    - name: image-name
      type: string
      description: The name of the image for the application
    - name: source-dir
      type: string
      default: /source
    - name: js-image
      type: string
      default: docker.io/node:12-stretch
    - name: tools-image
      type: string
      default: garagecatalyst/ibmcloud-dev:1.0.10
  volumes:
    - name: source
      emptyDir: {}
  steps:
    - name: git-clone
      image: alpine/git
      command: ["/bin/sh"]
      args:
        - -c
        - |
          git clone $(params.git-url) $(params.source-dir)
          cd $(params.source-dir)

          git reset --hard $(params.revision)

          echo ""
          echo "REVISION: $(params.revision)"
          echo "SOURCE_DIR: $(params.source-dir)"
          echo "IMAGE_URL: $(params.image-url)"
          echo "IMAGE_NAME: $(params.image-name)"
      volumeMounts:
        - name: source
          mountPath: $(params.source-dir)
    - name: health-check
      image: $(params.tools-image)
      workingdir: $(params.source-dir)
      env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      envFrom:
        - configMapRef:
            name: ibmcloud-config
      command: ["/bin/bash"]
      args:
        - -c
        - |
          ENVIRONMENT_NAME="${NAMESPACE}"

          IMAGE_NAME=$(params.image-name)

          if [[ "${CLUSTER_TYPE}" == "openshift" ]]; then
              ROUTE_HOST=$(kubectl get route/${IMAGE_NAME} --namespace ${ENVIRONMENT_NAME} --output=jsonpath='{ .spec.host }')
              URL="https://${ROUTE_HOST}"
          else
              INGRESS_HOST=$(kubectl get ingress/${IMAGE_NAME} --namespace ${ENVIRONMENT_NAME} --output=jsonpath='{ .spec.rules[0].host }')
              URL="http://${INGRESS_HOST}"
          fi
          # sleep for 10 seconds to allow enough time for the server to start
          sleep 30
          if [[ $(curl -sLk -w "%{http_code}\\n" "${URL}" -o /dev/null --connect-timeout 3 --max-time 5 --retry 3 --retry-max-time 30) == "200" ]]; then
              echo "Successfully reached Liberty Server endpoint: ${URL}"
              echo "====================================================================="
          else
              echo "Could not reach Liberty Server endpoint: ${URL}"
              exit 1;
          fi;
      volumeMounts:
        - name: source
          mountPath: $(params.source-dir)
