apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: igc-gradle-pact-verify
  labels:
    version: 0.0.0
spec:
  params:
    - name: repo-url
      description: The git repository url
    - name: revision
      description: The branch, tag, or git reference from the git repo-url location
      default: master
    - name: source-dir
      type: string
      default: /source
    - name: gradle-image
      type: string
      default: gradle:jdk11
    - name: tools-image
      type: string
      default: garagecatalyst/ibmcloud-dev:1.0.10
  volumes:
    - name: source
      emptyDir: {}
  stepTemplate:
    env:
      - name: GRADLE_USER_HOME
        value: $(params.source-dir)
  steps:
    - name: Git clone
      image: alpine/git
      command: ["/bin/bash"]
      args:
        - -c
        - |
          git clone $(params.repo-url) $(params.source-dir)
          cd $(params.source-dir)
          git checkout $(params.revision)
      volumeMounts:
        - name: source
          mountPath: $(params.source-dir)
    - name: setup
      image: $(params.tools-image)
      workingdir: $(params.source-dir)
      env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: BRANCH
          value: $(params.revision)
      envFrom:
        - configMapRef:
            name: ibmcloud-config
      command: ["/bin/bash"]
      args:
        - -c
        - |
          set -e
          git fetch --unshallow
          git fetch --tags
          git tag -l

          git checkout ${BRANCH}

          IMAGE_VERSION=$(git describe --abbrev=0 --tags)
          IMAGE_NAME=$(basename -s .git `git config --get remote.origin.url` | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g')

          if [[ "${CLUSTER_TYPE}" == "openshift" ]]; then
            HOST=$(kubectl get route/${IMAGE_NAME} --namespace ${NAMESPACE} --output=jsonpath='{ .spec.host }')
            PROTOCOL="https"
            PORT="443"
          else
            HOST=$(kubectl get ingress/${IMAGE_NAME} --namespace ${NAMESPACE} --output=jsonpath='{ .spec.rules[0].host }')
            PROTOCOL="http"
            PORT="80"
          fi

          echo "IMAGE_VERSION=${IMAGE_VERSION}" > ./env-config
          echo "IMAGE_NAME=${IMAGE_NAME}" >> ./env-config
          echo "HOST=${HOST}" >> ./env-config
          echo "PORT=${PORT}" >> ./env-config
          echo "PROTOCOL=${PROTOCOL}" >> ./env-config

          chmod a+w ./env-config
      volumeMounts:
        - name: source
          mountPath: $(params.source-dir)
    - name: pact-verify
      image: $(params.gradle-image)
      workingdir: $(params.source-dir)
      command: ["/bin/bash"]
      envFrom:
        - configMapRef:
            name: pactbroker-config
            optional: true
        - secretRef:
            name: pactbroker-access
            optional: true
      args:
        - -c
        - |
          set -e
          if [[ -z "${PACTBROKER_URL}" ]]; then
            echo "PactBroker url not set. Skipping pact verification"
            exit 0
          fi

          set -x
          . ./env-config

          if ./gradlew tasks --all | grep -Eq "^pactVerify"; then
              echo "Pact Verify task found"
          else
              echo "Skipping Pact Verify step, no task defined"
              exit 0
          fi

          ./gradlew pactVerify \
            -PpactBrokerUrl=${PACTBROKER_URL} \
            -PpactProtocol=${PROTOCOL} \
            -PpactHost=${HOST} \
            -PpactPort=${PORT} \
            -Ppact.verifier.publishResults=true
      volumeMounts:
        - name: source
          mountPath: $(params.source-dir)
