apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: igc-gitops-edge
  annotations:
    description: Registers the image with the Edge server using the hzn cli
  labels:
    version: 0.0.0
spec:
  volumes:
    - name: source
      emptyDir: {}
    - name: icp-ca
      secret:
        secretName: edge-access
        items:
          - key: HZN_CERTIFICATE
            path: icp-ca.crt
  params:
    - name: git-url
      type: string
      description: The git repository url
    - name: revision
      description: The git reference that was checked out
    - name: image-url
      type: string
      description: "The location where to push the image in the form of <server>/<namespace>/<repository>:<tag>"
    - name: image-name
      type: string
      description: The name of the image for the application
    - name: source-dir
      type: string
      default: /source
    - name: tools-image
      type: string
      default: garagecatalyst/ibmcloud-dev:1.1.3
  steps:
    - name: git-clone
      image: alpine/git
      command: ["/bin/sh"]
      args:
        - -c
        - |
          git clone $(params.git-url) $(params.source-dir)
          cd $(params.source-dir)

          git reset --hard $(params.revision)
      volumeMounts:
        - name: source
          mountPath: $(params.source-dir)
    - name: gitops-edge
      image: $(params.tools-image)
      workingdir: $(params.source-dir)
      securityContext:
        allowPrivilegeEscalation : true
      env:
        - name: HOME
          value: /home/devops
      envFrom:
        - configMapRef:
            name: ibmcloud-config
            optional: true
        - secretRef:
            name: edge-access
            optional: true
        - secretRef:
            name: ibmcloud-apikey
            optional: true
      volumeMounts:
        - mountPath: /opt/certs
          name: icp-ca
        - name: source
          mountPath: $(params.source-dir)
      command: ["/bin/bash"]
      args:
        - -c
        - |
          set -e
          set -x

          IMAGE_URL=$(params.image-url)
          IMAGE_NAME=$(params.image-name)

          REGISTRY_URL=$(echo $IMAGE_URL | awk -F / '{print $1}')
          REGISTRY_NAMESPACE=$(echo $IMAGE_URL | awk -F / '{print $2}')
          IMAGE_TAG=$(echo $IMAGE_URL | awk -F / '{print $3}')
          IMAGE_NAME=$(echo IMAGE_TAG | awk -F : '{print $1}')
          IMAGE_VERSION=$(echo IMAGE_TAG | awk -F : '{print $2}')

          if [[ -z "${HZN_EXCHANGE_URL}" ]]; then
            echo "Edge Exchange has not been configured. Skipping trigger step"
            exit 0
          fi

          if [[ -z "${HZN_EXCHANGE_USER_AUTH}" ]] || [[ -z "${HZN_CERTIFICATE}" ]]; then
            echo "Edge Credentials or Certificate not set"
            exit 1
          fi

          if [[ -z "${branch}" ]]; then
            branch="master"
          fi

          hzn version

          # Verify the Edge Cert is visible from the Tekton Task
          ls /opt/certs/*.crt

          cp /opt/certs/icp-ca.crt /usr/local/share/ca-certificates && update-ca-certificates

          APP_IMAGE="${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}"

          jq -n --arg HZN_ORG_ID "${HZN_ORG_ID}" \
            --arg APP_IMAGE "${APP_IMAGE}" \
            --arg IMAGE_NAME "${IMAGE_NAME}" \
            --arg IMAGE_VERSION "${IMAGE_VERSION}" \
            '{"HZN_ORG_ID": $HZN_ORG_ID, "MetadataVars": {"DOCKER_IMAGE_BASE": $APP_IMAGE,"SERVICE_NAME": $IMAGE_NAME,"SERVICE_VERSION": $IMAGE_VERSION} }' > ./horizon/hzn.json

          cat ./horizon/hzn.json

          # Publish Service to Edge Application Manager
          hzn key create "IBM" "user@us.ibm.com"

          make publish-service

          echo "Edge Service registered"
