apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ibm-appmod-liberty
  labels:
    version: 0.0.0
spec:
  params:
    - name: repo-url
    - name: revision
      default: master
    - name: image
    - name: image-tag
      default: latest
  tasks:
    - name: test
      taskRef:
        name: ibm-java-maven-test
      params:
        - name: image
          value: $(params.image):$(params.image-tag)
        - name: repo-url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
    - name: build
      taskRef:
        name: ibm-build-tag-push
      runAfter:
       - test
      params:
        - name: image
          value: $(params.image):$(params.image-tag)
        - name: repo-url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
    - name: deploy
      taskRef:
        name: ibm-deploy
      runAfter:
       - build
      params:
        - name: image
          value: $(params.image):$(params.image-tag)
        - name: repo-url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
    - name: health
      taskRef:
        name: ibm-liberty-server-check
      runAfter:
       - deploy
      params:
        - name: image
          value: $(params.image):$(params.image-tag)
        - name: repo-url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
    - name: package
      taskRef:
        name: ibm-helm-package
      runAfter:
       - health
      params:
        - name: image
          value: $(params.image):$(params.image-tag)
        - name: repo-url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
    - name: gitops
      taskRef:
        name: ibm-gitops
      runAfter:
       - package
      params:
        - name: image
          value: $(params.image):$(params.image-tag)
        - name: repo-url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
