apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: igc-nodejs
  labels:
    version: 0.0.0
spec:
  params:
    - name: repo-url
      type: string
      description: The url for the git repository
    - name: revision
      description: The git revision (branch, sha, tag) that should be built
      type: string
      default: master
    - name: image
      description: The url for the resulting image
      type: string
    - name: image-tag
      description: The tag that should be given the build image
      type: string
      default: latest
  tasks:
    - name: test
      taskRef:
        name: igc-nodejs-test
      params:
        - name: image
          value: $(params.image):$(params.image-tag)
        - name: repo-url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
    - name: build
      taskRef:
        name: igc-build-tag-push
      runAfter:
       - test
      params:
        - name: image
          value: $(params.image):$(params.image-tag)
        - name: repo-url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
    - name: deploy
      taskRef:
        name: igc-deploy
      runAfter:
       - build
      params:
        - name: image
          value: $(tasks.build.results.image)
        - name: repo-url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
    - name: health
      taskRef:
        name: igc-health-check
      runAfter:
       - deploy
      params:
        - name: image
          value: $(tasks.build.results.image)
        - name: repo-url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
    - name: release
      taskRef:
        name: igc-helm-package
      runAfter:
       - health
      params:
        - name: image
          value: $(tasks.build.results.image)
        - name: repo-url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
    - name: gitops
      taskRef:
        name: igc-gitops
      runAfter:
       - release
      params:
        - name: image
          value: $(tasks.release.results.image)
        - name: repo-url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
