apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: igc-nodejs
  labels:
    version: 0.0.0
spec:
  params:
    - name: git-url
      type: string
      description: The url for the git repository
    - name: revision
      description: The git revision (branch, tag, or sha) that should be built
      type: string
      default: master
    - name: image-url
      description: The url for the resulting image
      type: string
    - name: image-name
      description: The url for the resulting image
      type: string
      default: ""
    - name: image-tag
      description: The tag that should be given the build image
      type: string
      default: latest
  tasks:
    - name: setup
      taskRef:
        name: igc-setup
      params:
        - name: git-url
          value: $(params.git-url)
        - name: revision
          value: $(params.revision)
        - name: image-url
          value: $(params.image-url):$(params.image-tag)
        - name: image-name
          value: $(params.image-name)
    - name: test
      taskRef:
        name: igc-nodejs-test
      runAfter:
        - setup
      params:
        - name: git-url
          value: $(params.git-url)
        - name: revision
          value: $(tasks.setup.results.revision)
        - name: source-dir
          value: $(tasks.setup.results.source-dir)
        - name: image-url
          value: $(tasks.setup.results.image-url)
        - name: image-name
          value: $(tasks.setup.results.image-name)
    - name: build
      taskRef:
        name: igc-build-tag-push
      runAfter:
       - test
      params:
        - name: git-url
          value: $(params.git-url)
        - name: revision
          value: $(tasks.setup.results.revision)
        - name: image-url
          value: $(tasks.setup.results.image-url)
        - name: image-name
          value: $(tasks.setup.results.image-name)
        - name: source-dir
          value: $(tasks.setup.results.source-dir)
    - name: deploy
      taskRef:
        name: igc-deploy
      runAfter:
       - build
      params:
        - name: git-url
          value: $(params.git-url)
        - name: revision
          value: $(tasks.setup.results.revision)
        - name: image-url
          value: $(tasks.setup.results.image-url)
        - name: image-name
          value: $(tasks.setup.results.image-name)
        - name: source-dir
          value: $(tasks.setup.results.source-dir)
    - name: health
      taskRef:
        name: igc-health-check
      runAfter:
       - deploy
      params:
        - name: git-url
          value: $(params.git-url)
        - name: revision
          value: $(tasks.setup.results.revision)
        - name: image-url
          value: $(tasks.setup.results.image-url)
        - name: image-name
          value: $(tasks.setup.results.image-name)
        - name: source-dir
          value: $(tasks.setup.results.source-dir)
    - name: img-release
      taskRef:
        name: igc-img-release
      runAfter:
        - health
      params:
        - name: git-url
          value: $(params.git-url)
        - name: revision
          value: $(tasks.setup.results.revision)
        - name: image-url
          value: $(tasks.setup.results.image-url)
        - name: image-name
          value: $(tasks.setup.results.image-name)
        - name: source-dir
          value: $(tasks.setup.results.source-dir)
    - name: helm-release
      taskRef:
        name: igc-helm-package
      runAfter:
        - img-release
      params:
        - name: git-url
          value: $(params.git-url)
        - name: revision
          value: $(tasks.setup.results.revision)
        - name: image-url
          value: $(tasks.setup.results.image-url)
        - name: image-name
          value: $(tasks.setup.results.image-name)
        - name: source-dir
          value: $(tasks.setup.results.source-dir)
    - name: gitops
      taskRef:
        name: igc-gitops
      runAfter:
       - helm-release
      params:
        - name: git-url
          value: $(params.git-url)
        - name: revision
          value: $(tasks.setup.results.revision)
        - name: image-url
          value: $(tasks.setup.results.image-url)
        - name: image-name
          value: $(tasks.setup.results.image-name)
        - name: source-dir
          value: $(tasks.setup.results.source-dir)
